<?php
// NEGoods
// Copyright (C) 2014 Tonary Management System, Inc. All Rights Reserved.

class NEGoods{

	public $target_name = '商品マスタ';
	public $api_url = '/api_v1_master_goods/search';
	public $file_suffix = '_goods.csv';
	public $deleted_flag = 'goods_deleted_flag';
	public $query_sort = 'goods_id-asc';
	public $query_fields = 'goods_id,goods_representation_id,goods_name,goods_foreign_name,goods_type_id,goods_type_name,goods_merchandise_id,goods_merchandise_name,goods_forwarding_method_id,goods_forwarding_method_name,goods_status_id,goods_status_name,goods_delivery_id,goods_delivery_name,goods_supplier_id,goods_jan_code,goods_maker_name,goods_maker_kana,goods_maker_address,goods_maker_zip_code,goods_model_number,goods_color,goods_mall_category,goods_shop_category,goods_cost_price,goods_display_price,goods_selling_price,goods_foreign_selling_price,goods_wholesale_retail_ratio,goods_weight,goods_width,goods_length,goods_height,goods_release_date,goods_first_time_sold_date,goods_last_time_sold_date,goods_first_time_supplied_date,goods_last_time_supplied_date,goods_stock_constant,goods_order_point,goods_lot,goods_publication_date,goods_stock_management_flag,goods_note,goods_visible_flag,goods_tag,goods_location,goods_delivery_mail_flag,goods_delivery_mail_maximum_quality,goods_gift_ok_flg,goods_size,goods_maker_model_number,goods_stock_alert_mail_threshold,goods_wholesale_mortgage_threshold,goods_shipping_base_id,goods_mail_tag_id,goods_1_item,goods_2_item,goods_3_item,goods_4_item,goods_5_item,goods_6_item,goods_7_item,goods_8_item,goods_9_item,goods_10_item,goods_11_item,goods_12_item,goods_13_item,goods_14_item,goods_15_item,goods_16_item,goods_17_item,goods_18_item,goods_19_item,goods_20_item,goods_1_select_id,goods_1_select_name,goods_2_select_id,goods_2_select_name,goods_3_select_id,goods_3_select_name,goods_4_select_id,goods_4_select_name,goods_5_select_id,goods_5_select_name,goods_6_select_id,goods_6_select_name,goods_7_select_id,goods_7_select_name,goods_8_select_id,goods_8_select_name,goods_9_select_id,goods_9_select_name,goods_10_select_id,goods_10_select_name,goods_publication_pic_id,goods_publication_pic_name,goods_stock_wholesale_quantity,goods_deleted_flag,goods_creation_date,goods_last_modified_date,goods_last_modified_null_safe_date,goods_creator_id,goods_creator_name,goods_last_modified_by_id,goods_last_modified_by_null_safe_id,goods_last_modified_by_name,goods_last_modified_by_null_safe_name';
	public $tokens = array(
		array('syohin_code','goods_id')
		,array('sire_code','goods_supplier_id')
		,array('jan_code','goods_jan_code')
		,array('maker_name','goods_maker_name')
		,array('maker_kana','goods_maker_kana')
		,array('maker_jyusyo','goods_maker_address')
		,array('maker_yubin_bangou','goods_maker_zip_code')
		,array('kataban','goods_model_number')
		,array('iro','goods_color')
		,array('syohin_name','goods_name')
		,array('gaikoku_syohin_name','goods_foreign_name')
		,array('syohin_kbn','goods_type_id')
		,array('toriatukai_kbn','goods_merchandise_id')
		,array('genka_tnk','goods_cost_price')
		,array('hyoji_tnk','goods_display_price')
		,array('baika_tnk','goods_selling_price')
		,array('gaikoku_baika_tnk','goods_foreign_selling_price')
		,array('kake_ritu','goods_wholesale_retail_ratio')
		,array('omosa','goods_weight')
		,array('haba','goods_width')
		,array('okuyuki','goods_length')
		,array('takasa','goods_height')
		,array('yusou_kbn','goods_forwarding_method_id')
		,array('syohin_status_kbn','goods_status_id')
		,array('hatubai_bi','goods_release_date')
		,array('zaiko_teisu','goods_stock_constant')
		,array('hachu_ten','goods_order_point')
		,array('lot','goods_lot')
		,array('keisai_tantou','goods_publication_pic_id')
		,array('keisai_bi','goods_publication_date')
		,array('bikou','goods_note')
		,array('daihyo_syohin_code','goods_representation_id')
		,array('visible_flg','goods_visible_flag')
		,array('mail_tag','goods_mail_tag_id')
		,array('tag','goods_tag')
		,array('location','goods_location')
		,array('mail_send_flg','goods_delivery_mail_flag')
		,array('mail_send_num','goods_delivery_mail_maximum_quality')
		,array('gift_ok_flg','goods_gift_ok_flg')
		,array('size','goods_size')
		,array('org_select1','goods_1_select_id')
		,array('org_select2','goods_2_select_id')
		,array('org_select3','goods_3_select_id')
		,array('org_select4','goods_4_select_id')
		,array('org_select5','goods_5_select_id')
		,array('org_select6','goods_6_select_id')
		,array('org_select7','goods_7_select_id')
		,array('org_select8','goods_8_select_id')
		,array('org_select9','goods_9_select_id')
		,array('org_select10','goods_10_select_id')
		,array('org1','goods_1_item')
		,array('org2','goods_2_item')
		,array('org3','goods_3_item')
		,array('org4','goods_4_item')
		,array('org5','goods_5_item')
		,array('org6','goods_6_item')
		,array('org7','goods_7_item')
		,array('org8','goods_8_item')
		,array('org9','goods_9_item')
		,array('org10','goods_10_item')
		,array('org11','goods_11_item')
		,array('org12','goods_12_item')
		,array('org13','goods_13_item')
		,array('org14','goods_14_item')
		,array('org15','goods_15_item')
		,array('org16','goods_16_item')
		,array('org17','goods_17_item')
		,array('org18','goods_18_item')
		,array('org19','goods_19_item')
		,array('org20','goods_20_item')
		,array('maker_kataban','goods_maker_model_number')
		,array('zaiko_threshold','goods_stock_alert_mail_threshold')
		,array('orosi_threshold','goods_wholesale_mortgage_threshold')
		,array('hasou_houhou_kbn','goods_delivery_id')
		,array('hasoumoto_code','goods_shipping_base_id')
	);

}
