services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ozie_web
    ports:
      - "127.0.0.1:8003:80"
    volumes:
      # アプリケーションコード（現行サーバーと同じパス構造）
      - ./tool:/home/tonary/www/ozie/tool
      - ./tool_test:/home/tonary/www/ozie/tool_test
      - ./index.php:/home/tonary/www/ozie/index.php
      - ./style.css:/home/tonary/www/ozie/style.css
      - ./.htaccess:/home/tonary/www/ozie/.htaccess
      - ./datas:/home/tonary/www/ozie/datas

      # Config.php（機密情報、現行サーバーと同じパス）
      - ./docker/config/Config.php:/home/tonary/include/ozie/Config.php

      # 一時ディレクトリ（現行サーバーと同じパス）
      - ./docker/tmp:/home/tonary/tmp/ozie/tool

      # Apache設定
      - ./docker/apache/ozie.tonary.biz.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/apache/servername.conf:/etc/apache2/conf-enabled/servername.conf

      # PHP設定
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - TZ=Asia/Tokyo
    networks:
      - ozie_network

networks:
  ozie_network:
    driver: bridge
