<?php
// NEBackupPage
// Copyright (C) 2014 Tonary Management System, Inc. All Rights Reserved.

class NEBackupPage{

	public $target_name = '商品ページマスタの基本情報';
	public $api_url = '/api_v1_master_pagebase/search';
	public $file_suffix = '_page_kihon.csv';
	public $deleted_flag = 'page_base_deleted_flag';
	public $query_sort = 'page_base_goods_id-asc';
	public $query_fields = 'page_base_goods_id,page_base_goods_name,page_base_category1,page_base_category2,page_base_category3,page_base_category4,page_base_category5,page_base_selling_price,page_base_display_price,page_base_postage_type,page_base_postage_amount,page_base_tax_type,page_base_display_flag,page_base_catch_phrase1,page_base_catch_phrase2,page_base_description1,page_base_description2,page_base_description3,page_base_description4,page_base_description5,page_base_description6,page_base_description7,page_base_description8,page_base_description9,page_base_description10,page_base_keyword,page_base_img1_src,page_base_img1_alt,page_base_img2_src,page_base_img2_alt,page_base_img3_src,page_base_img3_alt,page_base_img4_src,page_base_img4_alt,page_base_img5_src,page_base_img5_alt,page_base_img6_src,page_base_img6_alt,page_base_img7_src,page_base_img7_alt,page_base_img8_src,page_base_img8_alt,page_base_img9_src,page_base_img9_alt,page_base_img10_src,page_base_img10_alt,page_base_v_horizontal_category,page_base_v_vertical_category,page_base_date_of_delivery,page_base_shipping_days,page_base_sale_amount,page_base_sale_start,page_base_sale_end,page_base_related_goods,page_base_brand_name,page_base_maker_name,page_base_model_number,page_base_maker_model_number,page_base_jan,page_base_goods_spec_text,page_base_length,page_base_length_unit,page_base_height,page_base_height_unit,page_base_width,page_base_width_unit,page_base_weight,page_base_weight_unit,page_base_color,page_base_gift,page_base_raw_materials,page_base_origin_country,page_base_origin_place,page_base_preservation_method,page_base_goods_condition,page_base_spec1,page_base_spec2,page_base_spec3,page_base_spec4,page_base_spec5,page_base_free1,page_base_free2,page_base_free3,page_base_free4,page_base_free5,page_base_free6,page_base_free7,page_base_free8,page_base_free9,page_base_free10,page_base_publication_date,page_base_publication_pic_id,page_base_publication_pic_name,page_base_page_status_id,page_base_page_status_name,page_base_deleted_flag,page_base_creation_date,page_base_last_modified_date,page_base_last_modified_null_safe_date,page_base_creator_id,page_base_creator_name,page_base_last_modified_by_id,page_base_last_modified_by_null_safe_id,page_base_last_modified_by_name,page_base_last_modified_by_null_safe_name';
	public $tokens = array(
		array('商品コード','page_base_goods_id')
		,array('商品名','page_base_goods_name')
		,array('店舗内カテゴリ１','page_base_category1')
		,array('店舗内カテゴリ２','page_base_category2')
		,array('店舗内カテゴリ３','page_base_category3')
		,array('店舗内カテゴリ４','page_base_category4')
		,array('店舗内カテゴリ５','page_base_category5')
		,array('販売価格','page_base_selling_price')
		,array('表示価格','page_base_display_price')
		,array('送料区分','page_base_postage_type')
		,array('個別送料','page_base_postage_amount')
		,array('税区分','page_base_tax_type')
		,array('表示・非表示','page_base_display_flag')
		,array('キャッチコピー１','page_base_catch_phrase1')
		,array('キャッチコピー２','page_base_catch_phrase2')
		,array('説明文１','page_base_description1')
		,array('説明文２','page_base_description2')
		,array('説明文３','page_base_description3')
		,array('説明文４','page_base_description4')
		,array('説明文５','page_base_description5')
		,array('説明文６','page_base_description6')
		,array('説明文７','page_base_description7')
		,array('説明文８','page_base_description8')
		,array('説明文９','page_base_description9')
		,array('説明文１０','page_base_description10')
		,array('キーワード','page_base_keyword')
		,array('画像URL１','page_base_img1_src')
		,array('画像URL１説明','page_base_img1_alt')
		,array('画像URL２','page_base_img2_src')
		,array('画像URL２説明','page_base_img2_alt')
		,array('画像URL３','page_base_img3_src')
		,array('画像URL３説明','page_base_img3_alt')
		,array('画像URL４','page_base_img4_src')
		,array('画像URL４説明','page_base_img4_alt')
		,array('画像URL５','page_base_img5_src')
		,array('画像URL５説明','page_base_img5_alt')
		,array('画像URL６','page_base_img6_src')
		,array('画像URL６説明','page_base_img6_alt')
		,array('画像URL７','page_base_img7_src')
		,array('画像URL７説明','page_base_img7_alt')
		,array('画像URL８','page_base_img8_src')
		,array('画像URL８説明','page_base_img8_alt')
		,array('画像URL９','page_base_img9_src')
		,array('画像URL９説明','page_base_img9_alt')
		,array('画像URL１０','page_base_img10_src')
		,array('画像URL１０説明','page_base_img10_alt')
		,array('項目選択肢　横軸名','page_base_v_horizontal_category')
		,array('項目選択肢　縦軸名','page_base_v_vertical_category')
		,array('納期','page_base_date_of_delivery')
		,array('発送までの日数','page_base_shipping_days')
		,array('セール価格','page_base_sale_amount')
		,array('セール開始日時','page_base_sale_start')
		,array('セール終了日時','page_base_sale_end')
		,array('関連商品','page_base_related_goods')
		,array('ブランド名','page_base_brand_name')
		,array('メーカー名','page_base_maker_name')
		,array('型番','page_base_model_number')
		,array('メーカー型番','page_base_maker_model_number')
		,array('JAN/EAN','page_base_jan')
		,array('商品の仕様','page_base_goods_spec_text')
		,array('寸法　長さ','page_base_length')
		,array('寸法　長さ　単位','page_base_length_unit')
		,array('寸法　高さ','page_base_height')
		,array('寸法　高さ　単位','page_base_height_unit')
		,array('寸法　幅','page_base_width')
		,array('寸法　幅　単位','page_base_width_unit')
		,array('重量','page_base_weight')
		,array('重量　単位','page_base_weight_unit')
		,array('色','page_base_color')
		,array('ギフト可','page_base_gift')
		,array('原材料','page_base_raw_materials')
		,array('原産国','page_base_origin_country')
		,array('産地','page_base_origin_place')
		,array('保存方法','page_base_preservation_method')
		,array('商品のコンディション','page_base_goods_condition')
		,array('スペック１','page_base_spec1')
		,array('スペック２','page_base_spec2')
		,array('スペック３','page_base_spec3')
		,array('スペック４','page_base_spec4')
		,array('スペック５','page_base_spec5')
		,array('フリーエリア１','page_base_free1')
		,array('フリーエリア２','page_base_free2')
		,array('フリーエリア３','page_base_free3')
		,array('フリーエリア４','page_base_free4')
		,array('フリーエリア５','page_base_free5')
		,array('フリーエリア６','page_base_free6')
		,array('フリーエリア７','page_base_free7')
		,array('フリーエリア８','page_base_free8')
		,array('フリーエリア９','page_base_free9')
		,array('フリーエリア１０','page_base_free10')
	);

}
